language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
  - jruby-19mode
  - jruby-20mode

notifications:
  email:
    on_failure: change
  slack:
    rooms:
      - douglas:CkaMdC9JhYYG1NVbRXnu6xLc#general
      - douglas:CkaMdC9JhYYG1NVbRXnu6xLc#infrastructure